/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UserInterface;

/**
 *
 * @author Rolando
 */
public class MainUI extends javax.swing.JFrame {

    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tabs = new javax.swing.JTabbedPane();
        ConfigurationTab = new javax.swing.JPanel();
        Config_label = new javax.swing.JLabel();
        General_label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dayDurationInput = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        deliveryDaysInput = new javax.swing.JTextPane();
        setConfiguration = new javax.swing.JButton();
        chasis_label3 = new javax.swing.JLabel();
        dayDuration_label = new javax.swing.JLabel();
        dayDuration_label1 = new javax.swing.JLabel();
        Lambog_label = new javax.swing.JLabel();
        chasis_label4 = new javax.swing.JLabel();
        Maserati_label = new javax.swing.JLabel();
        chasis_label = new javax.swing.JLabel();
        NickelodeonTab = new javax.swing.JPanel();
        Nickelodeon_label = new javax.swing.JLabel();
        CartoonNetworkTab = new javax.swing.JPanel();
        CN_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tabs.setBackground(new java.awt.Color(102, 102, 102));
        Tabs.setForeground(new java.awt.Color(255, 255, 255));
        Tabs.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        ConfigurationTab.setBackground(new java.awt.Color(51, 51, 51));
        ConfigurationTab.setForeground(new java.awt.Color(255, 255, 255));
        ConfigurationTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Config_label.setFont(new java.awt.Font("Microsoft YaHei", 1, 36)); // NOI18N
        Config_label.setForeground(new java.awt.Color(255, 255, 153));
        Config_label.setText("CONFIGURATION");
        ConfigurationTab.add(Config_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 330, 60));

        General_label.setBackground(new java.awt.Color(102, 102, 102));
        General_label.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        General_label.setForeground(new java.awt.Color(255, 255, 255));
        General_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        General_label.setText("GENERAL");
        ConfigurationTab.add(General_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 140, 40));

        dayDurationInput.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        dayDurationInput.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(dayDurationInput);

        ConfigurationTab.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 120, -1));

        deliveryDaysInput.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        deliveryDaysInput.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(deliveryDaysInput);

        ConfigurationTab.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 120, -1));

        setConfiguration.setBackground(new java.awt.Color(255, 255, 153));
        setConfiguration.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        setConfiguration.setForeground(new java.awt.Color(51, 51, 51));
        setConfiguration.setText("SET CONFIGURATION");
        setConfiguration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setConfigurationActionPerformed(evt);
            }
        });
        ConfigurationTab.add(setConfiguration, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 260, 50));

        chasis_label3.setBackground(new java.awt.Color(102, 102, 102));
        chasis_label3.setFont(new java.awt.Font("Microsoft YaHei", 1, 10)); // NOI18N
        chasis_label3.setForeground(new java.awt.Color(255, 255, 153));
        chasis_label3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chasis_label3.setText("You have to press the button to set the configuration");
        ConfigurationTab.add(chasis_label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 280, 30));

        dayDuration_label.setBackground(new java.awt.Color(102, 102, 102));
        dayDuration_label.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        dayDuration_label.setForeground(new java.awt.Color(255, 255, 255));
        dayDuration_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dayDuration_label.setText("Day Duration (seconds)");
        ConfigurationTab.add(dayDuration_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 170, 30));

        dayDuration_label1.setBackground(new java.awt.Color(102, 102, 102));
        dayDuration_label1.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        dayDuration_label1.setForeground(new java.awt.Color(255, 255, 255));
        dayDuration_label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dayDuration_label1.setText("Days to Deliver");
        ConfigurationTab.add(dayDuration_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 110, 30));

        Lambog_label.setBackground(new java.awt.Color(102, 102, 102));
        Lambog_label.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        Lambog_label.setForeground(new java.awt.Color(255, 255, 255));
        Lambog_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lambog_label.setText("NICKELODEON");
        ConfigurationTab.add(Lambog_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 210, 60));

        chasis_label4.setBackground(new java.awt.Color(102, 102, 102));
        chasis_label4.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        chasis_label4.setForeground(new java.awt.Color(255, 255, 153));
        chasis_label4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chasis_label4.setText("MAXIMUM 20 WORKERS");
        ConfigurationTab.add(chasis_label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 180, 30));

        Maserati_label.setBackground(new java.awt.Color(102, 102, 102));
        Maserati_label.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        Maserati_label.setForeground(new java.awt.Color(255, 255, 255));
        Maserati_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Maserati_label.setText("CARTOON NETWORK");
        ConfigurationTab.add(Maserati_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, 270, 60));

        chasis_label.setBackground(new java.awt.Color(102, 102, 102));
        chasis_label.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        chasis_label.setForeground(new java.awt.Color(255, 255, 153));
        chasis_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chasis_label.setText("MAXIMUM 12 WORKERS");
        ConfigurationTab.add(chasis_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 150, 170, 30));

        Tabs.addTab("Configuration", ConfigurationTab);

        NickelodeonTab.setBackground(new java.awt.Color(51, 51, 51));
        NickelodeonTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nickelodeon_label.setFont(new java.awt.Font("Microsoft YaHei", 1, 36)); // NOI18N
        Nickelodeon_label.setForeground(new java.awt.Color(255, 255, 153));
        Nickelodeon_label.setText("NICKELODEON");
        NickelodeonTab.add(Nickelodeon_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 290, 60));

        Tabs.addTab("Nickelodeon", NickelodeonTab);

        CartoonNetworkTab.setBackground(new java.awt.Color(51, 51, 51));
        CartoonNetworkTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CN_label.setFont(new java.awt.Font("Microsoft YaHei", 1, 36)); // NOI18N
        CN_label.setForeground(new java.awt.Color(255, 255, 153));
        CN_label.setText("CARTOON NETWORK");
        CartoonNetworkTab.add(CN_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 410, 60));

        Tabs.addTab("Cartoon Network", CartoonNetworkTab);

        getContentPane().add(Tabs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setConfigurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setConfigurationActionPerformed
        
    }//GEN-LAST:event_setConfigurationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CN_label;
    private javax.swing.JPanel CartoonNetworkTab;
    private javax.swing.JLabel Config_label;
    private javax.swing.JPanel ConfigurationTab;
    private javax.swing.JLabel General_label;
    private javax.swing.JLabel Lambog_label;
    private javax.swing.JLabel Maserati_label;
    private javax.swing.JPanel NickelodeonTab;
    private javax.swing.JLabel Nickelodeon_label;
    private javax.swing.JTabbedPane Tabs;
    private javax.swing.JLabel chasis_label;
    private javax.swing.JLabel chasis_label3;
    private javax.swing.JLabel chasis_label4;
    private javax.swing.JTextPane dayDurationInput;
    private javax.swing.JLabel dayDuration_label;
    private javax.swing.JLabel dayDuration_label1;
    private javax.swing.JTextPane deliveryDaysInput;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton setConfiguration;
    // End of variables declaration//GEN-END:variables
}
